# 异常
`异常` 导致程序的正常流程被中断的事件，叫做异常<br>

异常分为检查型异常(CheckedException，也叫可查异常)，非检查型异常(Error和RuntimeException，也叫不可查异常)以及错误(Errror)。RuntimeException包括数组越界，访问null指针，错误的强制转换；<br>

出现该类异常，一定是自己的问题。<br>

检查型异常(CheckedException): 如果不处理，编译器，就不让你通过

非检查型异常(Error和RuntimeException): 不是必须进行try catch的异常

编译器将检查你是否为所有的检查型异常提供了异常处理器<br>

下面的例子为利用java打开`d:/LOL.exe`,如果不做任何处理就会报错，Java编译器会强制你考虑两种情况:该文件存在与否<br>

`设计的面试问题：`<br>
运行时异常与非运行时异常的区别：
运行时异常是不可查异常，不需要进行显式的捕捉，但也可捕捉。
非运行时异常是可查异常，必须进行显式的捕捉，或者抛出

可查异常

`Java规定：` 对于可查异常必须捕捉、或者声明抛出。允许忽略不可查的RuntimeException和Error。Error也是可以catch的
```Java
package practice;

import java.io.File;
import java.io.FileInputStream;

public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		File f= new File("d:/LOL.exe");
        
        //试图打开文件LOL.exe，会抛出FileNotFoundException，如果不处理该异常，就会有编译错误
        new FileInputStream(f);
	}
}
```

因此强制考虑处理异常：<br>
1）利用try-catch<br>
```Java
package practice;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		File f= new File("d:/LOL.exe");
        
        //试图打开文件LOL.exe，会抛出FileNotFoundException，如果不处理该异常，就会有编译错误
        
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
        catch(FileNotFoundException e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
	}
}

编译结果：
试图打开 d:/LOL.exe
d:/LOL.exe不存在
java.io.FileNotFoundException: d:\LOL.exe (系统找不到指定的文件。)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at practice.Exception.main(Exception.java:17)
```
<br>
2)使用异常的父类进行catch<br>
FileNotFoundException是`Exception`的子类，使用Exception也可以catch住FileNotFoundException

```Java
package exception;
  
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
  
public class TestException {
  
    public static void main(String[] args) {
          
        File f= new File("d:/LOL.exe");
          
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
         
        catch(Exception e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
          
    }
}
```
3)多异常捕捉<br>
可能存在多个异常，如文件异常和解析异常，因此可使用多个catch
```Java
public class TestException {

	public static void main(String[] args) throws FileNotFoundException {
		// TODO Auto-generated method stub
        File f = new File("d:/LOL.exe");
        
        try {
            System.out.println("试图打开 d:/LOL2.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse("2016-06-03");
        } catch (FileNotFoundException e) {
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        } catch (ParseException e) {
            System.out.println("日期格式解析错误");
            e.printStackTrace();
        }
	}
}
```
此外还可将多个异常放在同一个catch里面，可用 `ininstanceof` 进行判断具体的异常类型
```Java
public class TestException {
 
    public static void main(String[] args) {
 
        File f = new File("d:/LOL.exe");
 
        try {
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse("2016-06-03");
        } catch (FileNotFoundException | ParseException e) {
            if (e instanceof FileNotFoundException)
                System.out.println("d:/LOL.exe不存在");
            if (e instanceof ParseException)
                System.out.println("日期格式解析错误");
 
            e.printStackTrace();
        }
 
    }
}
```
`finally` 无论异常与否，finally都会被调用

`throws` 抛出异常，一般利用函数调用
```Java
public class TestException {
 
    public static void main(String[] args) {
        method1();
 
    }
 
    private static void method1() {
        try {
            method2();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
 
    }
 
    private static void method2() throws FileNotFoundException {
 
        File f = new File("d:/LOL.exe");
 
        System.out.println("试图打开 d:/LOL.exe");
        new FileInputStream(f);
        System.out.println("成功打开");
 
    }
}
```
此例中，method2()抛出异常给method1()，由method1()的try和catch来处理异常; 如果一直将异常往外抛，抛到main()仍然不处理，那么最后就会抛到JVM，那么编译
就不能通过

抛出异常：
`throws与throw的区别`
1. throws 出现在方法声明上，而throw通常都出现在方法体内。
2. throws 表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某个异常对象。

`Throwable`  Exception和Error都继承了该类

Throwable类常用方法：  void printStackTrace()  将此 throwable 及其追踪输出至标准错误流 

多个catch并行：注意先后顺序，异常之间是否有继承关系。如果无继承关系，则先后顺序无关；若有继承关系，则父类异常应该在后，否则子类异常永远不会被捕获

Exception
    RunTimeException
       NullPointException
       IndexOutBoundException
	   ArrayIndexOutOfBoundException 	
```java
package exception;

public class ExcepDemo {
    public static void main(String[] args) {
        try {
            show(0);
        }catch (ArrayIndexOutOfBoundsException exception){
            System.out.println("数组越界");
        }catch (NullPointerException exception){
            System.out.println("空指针异常");
        }
    }

    public static void show(int a) {
        int[] array1 = new int[0];
        int[] array2 = null;
        if (a == 0) {
            System.out.println(array1[1]);
        } else {
            System.out.println(array2[1]);
        }
    }
}
```

四大运行异常: 越界异常，空指针，无效参数异常，类型转换

![Throwable类](https://github.com/ykangli/-/blob/master/742.png)

